#!/usr/bin/php
<?php
/**
 * @author stev leibelt <artodeto@bazzline.net>
 * @since 2015-02-07
 */

$options = array(
    '--source source/Net/Bazzline/Component/Locator/',
    '--destination document/',
    '--title "Locator Generator by Bazzline"'
);
$command = 'php vendor/bin/apigen generate ' . implode(' ', $options);
passthru($command);
